#!/usr/bin/env php
<?php
if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach ([
             __DIR__ . '/vendor/autoload.php',
             __DIR__ . '/../../autoload.php',
             __DIR__ . '/../vendor/autoload.php',
         ] as $file) {
    if (file_exists($file)) {
        define('ENGINE_AUTOLOAD', $file);
        break;
    }
}

unset($file);

if (!defined('ENGINE_AUTOLOAD')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require ENGINE_AUTOLOAD;

use Eva\EvaEngine\Dev;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Dev\Env());
$application->add(new Dev\MakeModule());
$application->add(new Dev\MakeApp());
$application->add(new Dev\MakeEntity());
$application->add(new Dev\MakeProject());
$application->add(new Dev\Exc());
$application->run();
