#!/usr/bin/env php
<?php
if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(
             __DIR__ . '/../../autoload.php',
             __DIR__ . '/../vendor/autoload.php',
             __DIR__ . '/vendor/autoload.php'
         ) as $file) {
    if (file_exists($file)) {
        define('PHPUNIT_COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

if (!defined('PHPUNIT_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}
//require PHPUNIT_COMPOSER_INSTALL;
require __DIR__ . '/vendor/autoload.php';

use Eva\EvaEngine\Dev\MakeModule;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new MakeModule());
$application->run();

